#!/usr/bin/env bash
# Script to configure Nginx with custom HTTP response header

# Update the package repository
apt-get -y update

# Install Nginx
apt-get -y install nginx

# Create a simple HTML file
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Add a custom 404 page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Configure Nginx to add custom header
nginx_config="/etc/nginx/nginx.conf"
sed -i "/include \/etc\/nginx\/sites-enabled\/\*;/a \\\n\tadd_header X-Served-By \"\$(hostname)\";" "$nginx_config"

# Restart Nginx to apply changes
service nginx restart
