#!/usr/bin/env bash
#this program prints Best School to 10
#when it reaches 9 it prints Best School and hi

counter=1
while [ $counter -le 10 ]
do
	echo "Best School"
	if ((counter == 9)); then
		echo "Hi"
	fi
	((counter++))
done
