#!/usr/bin/env bash
#script prints Best School 10 times using while loop
#at 4 it prints Best School and bad luck
#at 8 it prints Best School and good luck

counter=1

while [ $counter -le 10 ]
do
	if ((counter == 4)); then
		echo "Best School"
		echo "bad luck"
	elif ((counter == 8)); then
		echo "Best School"
		echo "good luck"
	else
		echo "Best School"
	fi
	
	((counter++))
done
