#!/usr/bin/env bash
#script that displays the time for 12 hours and 59 minutes using a while loop
#display hours from 0 to 12
#display minutes from 1 to 59

hours=0
minutes=1

while [ $hours -le 12 ]
do
	echo "Hour: $hours"
	while [ $minutes -le 59 ]
	do
		echo $minutes
		((minutes++))
	done
	minutes=1
	((hours++))
done
